[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"

[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.1.0"  
matplotlib = "^3.10.1" 
yfinance = "^0.2.55" 
pandas = "^2.0.3"
python-dateutil = "^2.8.2"
seaborn = "*"